#!/usr/bin/env bash
if [[ -z $1 ]];then
  echo "nothing to clone"
  echo "clone-atom <name-of-git-on-atom>"
  exit 1
fi

NAME=$(echo $1 | awk '!/\.git$/ { print $0".git" }')

if [[ -z $NAME ]];then
  NAME=$1
fi

echo "git clone ssh://git@95.165.133.121:4961/home/git/repo/${NAME}"
git clone ssh://git@95.165.133.121:4961/home/git/repo/${NAME}
