#!/usr/bin/env bash
CURRENT=$(pwd)

cd ${HOME}/git

if [[ -d ~/git/.local_arch ]]; then
  git_list=".local_arch"
fi

for git in $(ls -d */);
do
  git_list="$git_list $git"
done

echo && echo

for dir_name in $git_list
do
  cd $dir_name
  echo -e "\033[01;34m$(pwd)\033[00m"
  echo -e "\033[00;32m--------------------------------------------------------------------------------\033[00m"

  git config --get remote.origin.url
  echo
  git status
  cd ..
  echo -e "\033[00;32m________________________________________________________________________________\033[00m"
  echo "  "
  echo "  "
done

cd $CURRENT
