#!/usr/bin/env bash
UPG_LIST=("lb-lax" "vpn-gate" "vpn-madrid" "vpn-sfo3" "squid-devOps" "atom-devOps")

for ITEM in "${UPG_LIST[@]}"; do ssh $ITEM -t "echo -e \"\\033[01;31m_______________________________________________________________________________\\033[00m\"; echo; hostname | xargs echo -e \"\\033[01;33m\"; /home/master/git/exegit/git-pull-all && /home/master/git/ssh/ssh-update.sh; echo; echo"; done;
