#!/usr/bin/env bash
CURRENT_DIR=$(pwd)

if [[ -n ${1} ]]; then
  echo && echo
  SHORT_REPO_NAME="${1}"
  LOCAL_REPO_NAME="${HOME}/git/${1}"
  echo "New local local repository name: ${LOCAL_REPO_NAME}"
  REMOTE_REPO_NAME="/var/services/homes/tim/git/${1}.git";
  echo "New remote repository name: ${REMOTE_REPO_NAME}"
  echo && echo
else
  echo && echo
  echo "no git repository name provided"
  echo && echo
  exit 1
fi

ssh -p 4965 tim@ilyin.tech "bash -s "<<EOF
pwd;
mkdir -p ${REMOTE_REPO_NAME};
cd ${REMOTE_REPO_NAME};
pwd;
git init --bare;
EOF
echo && echo

cd ~/git
git clone ssh://tim@ilyin.tech:4965${REMOTE_REPO_NAME}
cd ${LOCAL_REPO_NAME}
pwd
ls -lah ${LOCAL_REPO_NAME}
echo && echo

git config --global fetch.prune true

echo -e "Project: ${SHORT_REPO_NAME}\n" | tee ${LOCAL_REPO_NAME}/README.md
ls -lah
echo && echo

git add . && git commit -m "initial commit"
echo && echo

git push -u origin master
# git branch --set-upstream-to=origin/master master

cd ${CURRENT_DIR}
