#!/usr/bin/env bash
CURRENT=$(pwd)
echo
echo "Checking git status for all repositories under ~/git"
echo "-----------------------------------------------------"
echo && echo

for GIT in $(find -H ~/git -type d -name '.git' -ls | awk '{ print $NF }'); do
  DIR="${GIT%\/.git}"
  cd ${DIR}
  echo -e "\033[01;34m$(pwd)\033[00m"
  echo -e "\033[00;32m--------------------------------------------------------------------------------\033[00m"

  git config --get remote.origin.url
  echo
  git status
  cd ..
  echo -e "\033[00;32m________________________________________________________________________________\033[00m"
  echo "  "
  echo "  "
done

cd $CURRENT
