#!/usr/bin/env bash
current_dir=$(pwd)

if [ -n $(which tldr) ]; then  
  TLDR_CONFIG=$(sudo grep -rnEI 'tldr-pages\/tldr\.git' ~/ | grep 'url = ' | awk -F: '{ print $1 }' | awk '!/git\// { print }')
  if [ -n "${TLDR_CONFIG}" ]; then
    TLDR_DIR=$(dirname "${TLDR_CONFIG}")
    TLDR_DIR="${TLDR_DIR%'/.git'}"
    dir_list="${dir_list} ${TLDR_DIR}"
    unset -v TLDR_CONFIG TLDR_DIR
  else
    echo "...update tldr snap"
    TLDR_GIT_PATH=$(grep -rnEI 'tldr-pages\/tldr.git' ${HOME}/ | grep -E '\.git\/config' | awk -F: '{ print $1 }')
    TLDR_GIT_PATH="${TLDR_GIT_PATH%%'/.git/config'}"
    [ -n "${TLDR_GIT_PATH}" ] && cd "${TLDR_GIT_PATH}"
    # tldr -u
    git pull
    cd ${HOME/git}
  fi
fi

cd $HOME/git
echo "Preparing repository list..."
dir_list=$(sudo find -H ./ -depth -type d -name '.git' -ls | awk '{ print $11 }' | awk -F / '{ print $1"/"$2 }' | sort)

if [[ -d $HOME/Documents ]];then
  dir_list="$dir_list $HOME/Documents"
fi

echo && echo
echo 'Detect network location...'
echo && echo

IS_DEVOPS_PING="$(ping -c3 10.58.0.250 | awk '/ 0% packet loss/ { print }')"

for dir_name in $dir_list; do
  cd $dir_name
  echo -e "\033[01;34m$(pwd)\033[00m"
  echo -e "\033[00;32m-------------------------------------------------------------------------------\033[00m"

  echo "Git reporitory set on: $(sed -E -n '/\surl = /p' .git/config)"
  
  if [[ -n "${IS_DEVOPS_PING}" ]]; then
    [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.58.0.250/g' .git/config && echo "Git reporitory now on: $(sed -E -n '/\surl = /p' .git/config)"
  elif [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.59.0' ]]; then
    echo "Git server is unreachable from this network -- connect to devOps"
    exit 1
  else
    [[ -n $(sed -n '/10.58.0.250/p' .git/config) ]] && sed -i 's/10.58.0.250/95.165.133.121/g' .git/config && echo "Git reporitory now on: $(sed -E -n '/\surl = /p' .git/config)"
  fi

  git pull

  if [[ "$dir_name" == "ssh" ]] && [ -f ~/git/ssh/ssh-update.sh ]; then
    . ~/git/ssh/ssh-update.sh
  fi

  cd $HOME/git
  echo -e "\033[00;32m_______________________________________________________________________________\033[00m"
  echo && echo
done

cd $current_dir

