#!/usr/bin/env bash
if [ $# eq 0 ]; then
  git branch --all
  echo
  read -p "Define branch to delete: " BRANCH  
else
  BRANCH="$1"
fi

echo "Branch to delete: ${BRANCH}"
read -p "Are you sure? Please confirm [Y/n]: " CONFIRM

if [ ${CONFIRM} == "n"]; then
  echo "ok, ${BRANCH} branch will not be deleted"
  exit 1
else
  echo "Delete branch ${BRANCH}"
  sleep 5s
  echo "---"
  git branch -D ${BRANCH}
  git push origin --delete ${BRANCH}
  echo "Clean up unused references.."
  git fetch --prune
fi