#!/usr/bin/env bash
if [[ -z "$1" ]]; then
  echo "There is no repository selected"
  exit 1
else
  REPO_NAME="$1"
  echo "git clone ${REPO_NAME}"
  [[ -z $(echo "${REPO_NAME}" | awk '/\.git$/{ print }') ]] && REPO_NAME=${REPO_NAME}.git
  git clone ssh://git@10.59.0.6:4964/home/git/repo/${REPO_NAME}
fi

echo
