#!/usr/bin/env bash
echo "usage: $0 {{comments}}"
echo
comments=$@

if [[ -z "$comments" ]]; then
  comments="work in progress as of $(date -u +%Y-%m-%dT%H:%M:%S%Z)"
  # Alternative date format $(date -u --rfc-3339=s)
  echo "auto comment set: $comments"
  echo
else
  comments="$comments at $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
  echo "$comments"
  echo
fi

CURRENT=$(pwd)
echo ${CURRENT}
while [[ ! $(ls -lah | awk '/\.git/ { print $9 }') ]]
do
  cd ..
done

git add .
echo
git commit -m "$comments"
echo
git push -u origin master

if [[ $(git config --get remote.origin.url) == *"github"* ]]; then
  echo "remote origin is on github.com"
else
  GIT_USER=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F@ ' { print $1 }')
  GIT_HOST=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F@ ' { print $2 }' | awk -F: '{ print $1 }')
  GIT_PORT=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F: '{ print $2 }')
  GIT_PREPATH=$(git config --get remote.origin.url | awk -F: '{ print $3 }')
  GIT_PATH=${GIT_PREPATH:${#GIT_PORT}:$((${#GIT_PREPATH}-1))}

  ssh -p ${GIT_PORT} ${GIT_USER}@${GIT_HOST} "cd ${GIT_PATH}; echo && echo \"${GIT_USER}@${GIT_HOST}:${GIT_PORT}${GIT_PATH}$ git push\"; git push;"
fi

cd ${CURRENT}
