#!/usr/bin/env bash
LIGHTRED='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

CURRENT=$(pwd)
cd $HOME/git

if [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.1.2' ]]; then
  [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.1.2.250/g' .git/config && REPO_IP='95.165.133.121'
elif [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.1.1' ]]; then
  echo "Git server is unreachable from this network -- got to devOps"
  exit 1
else
  [[ -n $(sed -n '/10.1.2.250/p' .git/config) ]] && sed -i 's/10.1.2.250/95.165.133.121/g' .git/config && REPO_IP='10.1.1.250'
fi

remote=""
remote=$(ssh -p 4965 tim@${REPO_IP} 'cd git; for dir in $(ls | grep .git); do echo $dir; done;')

local=""

for item in $remote; do
  local=$(echo $local)" "$(echo $item | awk -F. '{ print $1 }')
done;

for lgit in $local; do
  if [ -d $lgit ];then
    echo -e "${GREEN}$lgit${NC}"
    ls -lah $lgit
    echo
  else
    echo -e "${GREEN}$lgit${NC}"
    echo -e "${LIGHTRED}There is no $lgit locally${NC}"
    echo
  fi
done

cd $CURRENT
