#!/usr/bin/env bash
UPG_LIST=("vpn-gate" "vpn-madrid" "vpn-sfo3" "lb-lax" "squid-devOps" "atom-devOps")

for ITEM in "${UPG_LIST[@]}"; do ssh $ITEM -t "echo -e \"\\033[01;31m_______________________________________________________________________________\\033[00m\"; echo; echo -e \"\\033[01;33m$(hostname)\\033[00m\"; /home/master/git/exegit/git-pull-all && /home/master/git/ssh/ssh-update.sh; echo; echo"; done;
