#!/usr/bin/env bash
LIGHTRED='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

CURRENT=$(pwd)
cd $HOME/git

if [[ $(curl -s https://ipinfo.io/ip) == '95.165.133.121' ]]; then
  REPO_IP='10.1.1.250'
else
  REPO_IP='95.165.133.121'
fi

remote=""
remote=$(ssh -p 4965 tim@${REPO_IP} 'cd git; for dir in $(ls | grep .git); do echo $dir; done;')

local=""

for item in $remote; do
  local=$(echo $local)" "$(echo $item | awk -F. '{ print $1 }')
done;

for lgit in $local; do
  if [ -d $lgit ];then
    echo -e "${GREEN}$lgit${NC}"
    ls -lah $lgit
    echo
  else
    echo -e "${GREEN}$lgit${NC}"
    echo -e "${LIGHTRED}There is no $lgit locally${NC}"
    echo
  fi
done

cd $CURRENT
