#!/usr/bin/env bash
current_dir=$(pwd)

cd $HOME/git
dir_list=$(sudo find -H ./ -depth -name '.git' -ls | awk '{ print $11 }' | awk -F / '{ print $1"/"$2 }')
dir_list="$dir_list $HOME/Documents"

for dir_name in $dir_list
do
  cd $dir_name
  echo
  echo -e "\033[01;34m$(whoami)@$(hostname):$(pwd)\033[00m"
  echo -e "\033[00;32m---------------------------------------------------------------------------------\033[00m"

  if [[ $(curl -s https://ipinfo.io/ip) == '95.165.133.121' ]]; then
    [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.1.1.250/g' .git/config
  else
    [[ -n $(sed -n '/10.1.1.250/p' .git/config) ]] && sed -i 's/10.1.1.250/95.165.133.121/g' .git/config
  fi
    
  git status | awk '{ if( $0 ~ /^\// && $0 !~ /origin\/master/) { DIR=$0; print "DIR: " DIR; }; if( $0 ~ /Untracked/ || $0 ~ /Changes to be committed/ || $0 ~ /not staged for commit/){ system("git status && git add . && git commit -m \"work in progress as of $(date -u +%Y-%m-%d_at_%H:%M:%S_%Z) \" && echo && git push") } }'

  if [[ $(echo $(git config --get remote.origin.url)) =~ "ssh://" ]]; then
    GIT_USER=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F@ ' { print $1 }')
    GIT_HOST=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F@ ' { print $2 }' | awk -F: '{ print $1 }')
    GIT_PORT=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F: '{ print $2 }')
    GIT_PREPATH=$(git config --get remote.origin.url | awk -F: '{ print $3 }')
    GIT_PATH=${GIT_PREPATH:${#GIT_PORT}:$((${#GIT_PREPATH}-1))}

    ssh -p ${GIT_PORT} ${GIT_USER}@${GIT_HOST} "cd ${GIT_PATH}; echo; pwd; echo \"${GIT_USER}@${GIT_HOST}:${GIT_PORT}${GIT_PATH}$ git push\"; git push;"
  fi

  cd $HOME/git
  echo -e "\033[00;32m_________________________________________________________________________________\033[00m"
  echo "  "
  echo "  "
done

cd $current_dir
