#!/usr/bin/env bash
current_dir=$(pwd)

cd $HOME/git
dir_list=$(sudo find -H ./ -depth -name '.git' -ls | awk '{ print $11 }' | awk -F / '{ print $1"/"$2 }' | sort)

if [[ -d $HOME/Documents ]];then
  dir_list="$dir_list $HOME/Documents"
fi

echo && echo

for dir_name in $dir_list; do
  cd $dir_name
  echo -e "\033[01;34m$(pwd)\033[00m"
  echo -e "\033[00;32m-------------------------------------------------------------------------------\033[00m"

  sed -n '/url = ssh:\/\/tim@/p' .git/config

  if [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.1.2' ]]; then
    [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.1.2.250/g' .git/config
  elif [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.1.1' ]]; then
    echo "Git server is unreachable from this network -- connect to devOps"
    exit 1
  else
    [[ -n $(sed -n '/10.1.2.250/p' .git/config) ]] && sed -i 's/10.1.2.250/95.165.133.121/g' .git/config
  fi

  git pull

  if [[ "$dir_name" == "ssh" ]] && [ -f ~/git/ssh/ssh-update.sh ]; then
    . ~/git/ssh/ssh-update.sh
  fi

  cd $HOME/git
  echo -e "\033[00;32m_______________________________________________________________________________\033[00m"
  echo && echo
done

cd $current_dir

