#!/usr/bin/env bash
echo "usage: $0 {{comments}}"
comments=$@

if [[ -z "$comments" ]]; then
  comments="work in progress as of $(date -u +%Y-%m-%dT%H:%M:%S%Z)"
  # Alternative date format $(date -u --rfc-3339=s)
  echo "auto comment set: $comments"
else
  comments="$comments at $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
  echo "$comments"
fi

git add .
git commit -m "$comments"
git push

if [[ $(git config --get remote.origin.url) == *"95.165.133.121"* ]]; then
  ssh atom-58-inet "cd git/$(basename $(pwd)).git; echo && echo \"master@dsm:/var/services/home/tim/git/$(basename $(pwd)).git$ git push\"; git push;"
fi
