#!/usr/bin/env bash
CURRENT=$(pwd)

while [[ ! -f $(pwd)/.git/config && $(pwd) != '/' ]]
do
  cd ..
done

pwd

if [[ $(curl -s https://ipinfo.io/ip) == '95.165.133.121' ]]; then
  [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.1.1.250/g' .git/config
else
  [[ -n $(sed -n '/10.1.1.250/p' .git/config) ]] && sed -i 's/10.1.1.250/95.165.133.121/g' .git/config
fi

if [[ -f $(pwd)/.git/config ]]; then
  git status
  git pull
fi

cd ${CURRENT}
