#!/usr/bin/env bash
CURRENT=$(pwd)
cd ~/git

DIRS=".local_arch $(ls -d */)"
echo ${DIRS}

for DIR in ${DIRS}; do
  echo
  DIR=$(echo ${DIR} | sed 's:/*$::')
  echo ${DIR}
  sed -i -e '/url = ssh/d' -e "/\[remote \"origin\"\]/ a \\\turl = ssh:\/\/git@10.59.0.6:4964\/home\/git\/repo\/${DIR}.git" ${DIR}/.git/config
  echo
  
  cd ${DIR}
  BRANCH=$(git branch --all | awk '/^\*/{ print $2 }')
  git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
  git pull
  cd ~/git

  echo
done
echo

cd ${CURRENT}
