#!/usr/bin/env bash

echo "usage: $0 {{comments}}"
echo
comments=$@

if [[ -z "$comments" ]]; then
  comments="$(hostname): work in progress as of $(date -u +%Y-%m-%dT%H:%M:%S%Z)"
  # Alternative date format $(date -u --rfc-3339=s)
  echo "auto comment set: $comments"
  echo
else
  comments="$(hostname): $comments at $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
  echo "$comments"
  echo
fi

CURRENT=$(pwd)
echo ${CURRENT}
while [[ ! $(ls -lah | awk '/\.git/ { print $9 }') ]]
do
  cd ..
done

# if [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.58.0' ]]; then
#   [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.58.0.250/g' .git/config
# elif [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.59.0' ]]; then
#   echo "Git server is unreachable from this network -- got to devOps"
#   exit 1
# else
#   [[ -n $(sed -n '/10.58.0.250/p' .git/config) ]] && sed -i 's/10.58.0.250/95.165.133.121/g' .git/config
# fi

# git add .
echo
git commit -a -m "$comments" --status
echo
git push -u origin master

if [[ $(git config --get remote.origin.url) == *"github"* ]]; then
  echo "Done: remote origin is on github.com"
else
  GIT_USER=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F@ ' { print $1 }')
  GIT_HOST=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F@ ' { print $2 }' | awk -F: '{ print $1 }')
  GIT_PORT=$(git config --get remote.origin.url | awk -F/ '{ print $3 }' | awk -F: '{ print $2 }')
  GIT_PREPATH=$(git config --get remote.origin.url | awk -F: '{ print $3 }')
  GIT_PATH=${GIT_PREPATH:${#GIT_PORT}:$((${#GIT_PREPATH}-1))}

  ssh -p ${GIT_PORT} ${GIT_USER}@${GIT_HOST} "cd ${GIT_PATH}; echo; pwd; echo \"${GIT_USER}@${GIT_HOST}:${GIT_PORT}${GIT_PATH}$ git push\"; git push;"
fi

cd ${CURRENT}
