#!/usr/bin/env bash
LIGHTRED='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

CURRENT=$(pwd)
cd $HOME/git

remote=""
remote=$(ssh atom-58-inet 'cd git; for dir in $(ls | grep .git); do echo $dir; done;')

local=""

for item in $remote; do
  local=$(echo $local)" "$(echo $item | awk -F. '{ print $1 }')
done;

for lgit in $local; do
  if [ -d $lgit ];then
    echo -e "${GREEN}$lgit${NC}"
    ls -lah $lgit
    echo
  else
    echo -e "${GREEN}$lgit${NC}"
    echo -e "${LIGHTRED}There is no $lgit locally${NC}"
    echo
  fi
done

cd $CURRENT
