#!/usr/bin/env bash
CURRENT=$(pwd)

while [[ ! -f $(pwd)/.git/config && $(pwd) != '/' ]]
do
  cd ..
done

pwd

if [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.1.2' ]]; then
  [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.1.2.250/g' .git/config
elif [[ $(hostname -I | awk '{ print $1 }' | awk -F. '{ print $1"."$2"."$3}') == '10.1.1' ]]; then
  echo "Git server is unreachable from this network -- got to devOps"
  exit 1
else
  [[ -n $(sed -n '/10.1.2.250/p' .git/config) ]] && sed -i 's/10.1.2.250/95.165.133.121/g' .git/config
fi

if [[ -f $(pwd)/.git/config ]]; then
  git status
  git pull
fi

cd ${CURRENT}
