#!/usr/bin/env bash
CURRENT=$(pwd)

cd ${HOME}/git

if [[ -d ~/git/.local_arch ]]; then
  git_list=".local_arch"
fi

for git in $(ls -d */);
do
  git_list="$git_list $git"
done

if [[ -d ${HOME}/Documents ]]; then
  git_list="$git_list ${HOME}/Documents"
fi

echo && echo

for dir_name in $git_list
do
  cd $dir_name
  echo -e "\033[01;34m$(pwd)\033[00m"
  echo -e "\033[00;32m--------------------------------------------------------------------------------\033[00m"

  if [[ $(curl -s https://ipinfo.io/ip) == '95.165.133.121' ]]; then
    [[ -n $(sed -n '/95.165.133.121/p' .git/config) ]] && sed -i 's/95.165.133.121/10.1.1.250/g' .git/config
  else
    [[ -n $(sed -n '/10.1.1.250/p' .git/config) ]] && sed -i 's/10.1.1.250/95.165.133.121/g' .git/config
  fi

  git config --get remote.origin.url
  echo
  git status
  cd ..
  echo -e "\033[00;32m________________________________________________________________________________\033[00m"
  echo "  "
  echo "  "
done

cd $CURRENT
