#!/usr/bin/env bash
#
echo "usage: $0 {{comments}}"
comments=$@

if [[ -z "$comments" ]]; then
  comments="commit as of $(date -u +%Y-%m-%dT%H:%M:%S%Z)"
  # Alternative date format $(date -u --rfc-3339=s)
  echo "auto comment set: $comments"
else
  comments="$comments at $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
  echo "$comments at $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
fi

git add .
git commit -m "$comments"
git push
