#!/usr/bin/env bash
#
echo "usage: $0 {{comments}}"
comments=$@

if [[ -z "$comments" ]]; then
  comments="commit as of $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
  echo "auto set: $comments"
else
  echo "$comments at $(date -u +%Y-%m-%d_T_%H:%M:%S_%Z)"
fi

git add .
git commit -m "$comments"
git push
