#!/usr/bin/env bash
CURRENT=$(pwd)

cd ${HOME}/git
git_list=".local_arch"

for git in $(ls -d */);
do
  git_list="$git_list $git"
done

 git_list="$git_list ${HOME}/Documents"

for git in $git_list;
do
  cd $git
  echo
  pwd
  #sed -i 's/tim@95.165.133.121:4965\/var\/services\/homes\/tim\/git/tim@10.1.1.250:4965\/var\/services\/homes\/tim\/git/g' .git/config
  sed -i 's/tim@10.1.1.250:4965\/var\/services\/homes\/tim\/git/tim@95.165.133.121:4965\/var\/services\/homes\/tim\/git/g' .git/config
  cd ..
  echo
done

cd ${CURRENT}